version: '3.7'
services:
  backend:
    image: backend-api:1.0
    container_name: backend
    volumes:
      - ../:/usr/src/app
    ports:
      - 8899:8899
      - 80:80
      - 443:443
    tty: true
    networks:
      - webnet
networks:
  webnet: